### ISSUE TITLE
Publish to Curseforge

### ISSUE THREAD

**Issue by Madis0** [dlee13/hold-that-chunk#1]
For modpacks and more exposure :)

**Comment by dlee13** [comment]
Waiting for project approval, it will be here: https://www.curseforge.com/minecraft/mc-mods/hold-that-chunk

**Comment by Madis0** [comment]
Seems to be live now. To avoid interruptions with custom launchers (e.g. MultiMC, PolyMC), it would be nice of you to enable "distribution outside CurseForge" toggle as well.

**Comment by dlee13** [comment]
Done.
