### ISSUE TITLE
Crashing involving HTC

### ISSUE THREAD

**Issue by FnigePython** [dlee13/hold-that-chunk#10]
[crash-2022-09-28_19.17.49-client.txt](https://github.com/dlee13/hold-that-chunk/files/9663433/crash-2022-09-28_19.17.49-client.txt)

MC Version: 1,19.2
Modloader: Quilt 0.17.5-beta.3
QFAPI: 4.0.0-beta.13+0.62.0-1.19.2
HTC: 1.1.1

**Comment by dlee13** [comment]
Hello, thank you for this report.
I believe this crash is entirely avoided in the v2.0.0 implementation which has not been released yet.
