### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by Imzxhir** [dlee13/hold-that-chunk#13]
I'm getting multiple lines of 'Ignoring chunk since it's not in the view range: -259, -418', here is my log: https://mclo.gs/FcXj7B9. I'm using Hold That Chunk 2.0.1

**Comment by dlee13** [comment]
That is very strange, but there is no information for where that log is coming from. And I am unable to reproduce it on my end.

**Comment by dlee13** [comment]
After looking around the Minecraft client code, I found where that log comes from. It happens when the server sends the client chunk data for chunks that are outside of the client's view distance. I believe that it's not caused by Hold That Chunk.

**Comment by dlee13** [comment]
Is it happening consistently? If yes, please check that it doesn't happen when Hold That Chunk is disabled and starts happening again when Hold That Chunk is reenabled.

**Comment by dlee13** [comment]
The issue is probably caused by the server and has nothing to do with Hold That Chunk. That log would be triggered regardless of whether Hold That Chunk is installed or not.
