### ISSUE TITLE
Ignore server render distance has no effect

### ISSUE THREAD

**Issue by Julienraptor01** [dlee13/hold-that-chunk#18]
I tested it to understand the effect but no matter what i do it doesn't change anything and work the same way on and off
i tried in multiplayer on a server which had 8 render distance and my client was ignoring it and still rendering 16 chunks no matter if it was on or off
and i tried on single player and it didn't change anything either
my settings are 16 render distance and 64 unload distance

**Comment by dlee13** [comment]
The vanilla behavior for the Minecraft client is to take your client's render distance setting and the server's render distance setting and clamp down to the lower value of them. The purpose of the Ignore server render distance setting is to always use your client's render distance setting. When the server has 8 render distance and you have 16 render distance in the client settings, seeing 16 render distance with it on is as intended. You would have 8 render distance with it off.

One more caveat is that it only has an effect when you receive a join packet or render distance change packet from the server. So if you change the setting, you would have to leave and rejoin the server or travel between dimensions for the render distance to change.

This mod is completely nonfunctional in single player.

**Comment by Julienraptor01** [comment]
> The vanilla behavior for the Minecraft client is to take your client's render distance setting and the server's render distance setting and clamp down to the lower value of them. The purpose of the Ignore server render distance setting is to always use your client's render distance setting. When the server has 8 render distance and you have 16 render distance in the client settings, seeing 16 render distance with it on is as intended. You would have 8 render distance with it off.
> 
> One more caveat is that it only has an effect when you receive a join packet or render distance change packet from the server. So if you change the setting, you would have to leave and rejoin the server or travel between dimensions for the render distance to change.
> 
> This mod is completely nonfunctional in single player.

The thing is with both it on and off i had 16 render distance while the server had 8

**Comment by andrwcrr** [comment]
this isnt working for me either

**Comment by dlee13** [comment]
If you take the screenshots to verify that this issue is valid, we can reopen it for discussion. As it stands, there is nothing to be done about it since I can't tell what you're experiencing and I am unable to reproduce it.
