### ISSUE TITLE
Chunks turn invisible

### ISSUE THREAD

**Issue by TechPro424** [dlee13/hold-that-chunk#19]
Chunks turn invisible when joining servers

Join a server
Chunks turn invisible after a minute or so after joining server

![image](https://user-images.githubusercontent.com/86620085/226084680-d97103ba-4593-44fc-841d-29cc94dd8133.png)

MC Log: https://mclo.gs/vgnefT9
Modlist: https://moddermore.net/list/0abc8f29a9

**Comment by dlee13** [comment]
Have you tested whether the issue does not occur when Hold That Chunk is not installed?
Judging by the mention of a GL error in the log, I'm more inclined to think that this is a rendering bug caused by one of your other installed mods.

**Comment by TechPro424** [comment]
Yes, issue does occur even without this mod
My bad
