### ISSUE TITLE
fog doesnt render 

### ISSUE THREAD

**Issue by Moonyol** [dlee13/hold-that-chunk#22]
fabric 0.14.21 hold that chunk v2.0.1 1.20.1

**Comment by dlee13** [comment]
Does the fog render if you start the game with all the same mods except for Hold That Chunk?

**Comment by Moonyol** [comment]
yes by itself it doesnt render the fog

**Comment by dlee13** [comment]
This mod doesn't touch rendering at all, so this doesn't make sense to me.

What setting do you have for Ignore Server Render Distance? And how high is your Render Distance? What other client mods are you using?

**Comment by Moonyol** [comment]
sorry this was a month ago and i dont know how to reproduce it anymore because it looks fine

**Comment by dlee13** [comment]
I doubt it was caused by Hold That Chunk to begin with.
