### ISSUE TITLE
Hello, I'm asking you to make fabric or quilt for version 1.20.2 on morinth, thank you very much!

### ISSUE THREAD

**Issue by verixyt3** [dlee13/hold-that-chunk#23]
Hello, I'm asking you to make fabric or quilt for version 1.20.2 on morinth, thank you very much!

**Comment by TechPro424** [comment]
Bump

**Comment by dlee13** [comment]
The code has been updated with support for 1.20.2, but now it's time for me to go to my day job. Release to Modrinth/Curseforge should be in about 12 hours, but if you want to start using it early, you may download a build from [Actions](https://github.com/dlee13/hold-that-chunk/actions).
