### ISSUE TITLE
Allow higher render distances in servers

### ISSUE THREAD

**Issue by Madis0** [dlee13/hold-that-chunk#6]
As the mod is said to be an alternative to Bobby, and seems functionally similar to Farsight, I thought this feature was already included in the mod. However, two testers on my modpack pointed out that this mod does _not_ keep the chunks visible when they are cached but the player moves away from them (it still respects the server's rendering distance, not client's).

So, considering that the timed chunk unloading is still a performance benefit of this mod over the other two, could you add this feature as well? It could be opt-in by config, if you so choose.

Related: #5

**Comment by dlee13** [comment]
Yes, this mod currently respects the server's view distance, which is what I'd meant to convey in the description about how this differs from Bobby.

I can add a config for that, but I don't know whether it should be something like a boolean `force-client-render-distance` option and uses the value from your video settings. Or whether it should be an integer option that is used and setting it negative disables it.

**Comment by Madis0** [comment]
> I can add a config for that, but I don't know whether it should be something like a boolean force-client-render-distance option and uses the value from your video settings. 

It should indeed respect the vanilla setting, otherwise it just gets more confusing.

**Comment by dlee13** [comment]
Sounds good to me. This is planned for the next release. However, I think I will not get to work on it until Wednesday.

**Comment by dlee13** [comment]
This is in the v1.1.0 release.
