### ISSUE TITLE
Use simple or no warnings for config 

### ISSUE THREAD

**Issue by Madis0** [dlee13/hold-that-chunk#7]
I was thinking about the v1.1.1 approach, the config errors in the log are ugly and other mods don't really do that.

It would be better to replace the detailed errors with simple warnings ("variable" was not found in config, using default) or better yet, no warnings at at all, because other mods also silently fallback to defaults when a config entry is not found.

**Comment by dlee13** [comment]
I will make the warnings simple in the next version release.
